using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.AI.Local.Analyzers;

/// <summary>
/// Registers the provider packages an app references with the model catalog. For every referenced assembly that
/// declares <c>[assembly: LocalModelProvider(packageId, typeof(Registration))]</c>, the generator emits a module
/// initializer that calls <c>Registration.Register()</c>, so catalog handles such as <c>LanguageModels.Phi4Mini</c>
/// bind to their implementation without setup code, reflection or assembly scanning (trimming and Native AOT safe).
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ProviderRegistrationGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var enabled = context.AnalyzerConfigOptionsProvider.Select(static (options, _) =>
            !options.GlobalOptions.TryGetValue("build_property.MicrosoftAILocalAutoRegisterProviders", out var value) ||
            !string.Equals(value.Trim(), "false", StringComparison.OrdinalIgnoreCase));

        var registrations = context.CompilationProvider.Select(static (compilation, _) =>
        {
            if (compilation.GetTypeByMetadataName("System.Runtime.CompilerServices.ModuleInitializerAttribute") is null)
            {
                return new EquatableArray(ImmutableArray<string>.Empty);
            }

            var calls = LocalModelProviders.GetReferencedProviders(compilation)
                .Where(p => p.RegistrationType.DeclaredAccessibility == Accessibility.Public && HasRegisterMethod(p.RegistrationType))
                .Select(p => p.RegistrationType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .Distinct(StringComparer.Ordinal)
                .ToImmutableArray();
            return new EquatableArray(calls);
        });

        context.RegisterSourceOutput(registrations.Combine(enabled), static (spc, input) =>
        {
            var (types, isEnabled) = input;
            if (!isEnabled || types.Items.IsEmpty)
            {
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by Microsoft.AI.Local: registers the referenced model provider packages with the model catalog.");
            sb.AppendLine("// Set <MicrosoftAILocalAutoRegisterProviders>false</MicrosoftAILocalAutoRegisterProviders> to turn this off.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace Microsoft.AI.Local.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class LocalModelProviderRegistration");
            sb.AppendLine("    {");
            sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine("        internal static void RegisterProviders()");
            sb.AppendLine("        {");
            foreach (var type in types.Items)
            {
                sb.Append("            ").Append(type).AppendLine(".Register();");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            spc.AddSource("LocalModelProviderRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static bool HasRegisterMethod(INamedTypeSymbol type) =>
        type.GetMembers("Register").OfType<IMethodSymbol>().Any(m =>
            m.IsStatic && m.Parameters.IsEmpty && m.DeclaredAccessibility == Accessibility.Public);

    private readonly struct EquatableArray(ImmutableArray<string> items) : IEquatable<EquatableArray>
    {
        public ImmutableArray<string> Items { get; } = items.IsDefault ? ImmutableArray<string>.Empty : items;

        public bool Equals(EquatableArray other) => Items.SequenceEqual(other.Items, StringComparer.Ordinal);

        public override bool Equals(object? obj) => obj is EquatableArray other && Equals(other);

        public override int GetHashCode()
        {
            var hash = 17;
            foreach (var item in Items)
            {
                hash = (hash * 31) + StringComparer.Ordinal.GetHashCode(item);
            }

            return hash;
        }
    }
}
