using System;
using System.Collections.Immutable;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.AI.Local.Foundry.Generators;

/// <summary>
/// Emits the <c>FoundryModels</c> handle properties (with XML docs and <c>[Obsolete]</c> for retired models) from the
/// <c>foundry-models.json</c> catalog manifest passed as an AdditionalFile.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class FoundryModelsGenerator : IIncrementalGenerator
{
    /// <summary>The manifest file name.</summary>
    public const string ManifestFileName = "foundry-models.json";

    internal static readonly DiagnosticDescriptor InvalidManifest = new(
        "MSAILOCALGEN001",
        "Invalid Foundry catalog manifest",
        "The Foundry catalog manifest '{0}' is invalid: {1}",
        "Microsoft.AI.Local.Foundry",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor MultipleManifests = new(
        "MSAILOCALGEN002",
        "Multiple Foundry catalog manifests",
        "Only one '" + ManifestFileName + "' AdditionalFile is allowed; found {0}",
        "Microsoft.AI.Local.Foundry",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var manifests = context.AdditionalTextsProvider
            .Where(static file => string.Equals(Path.GetFileName(file.Path), ManifestFileName, StringComparison.OrdinalIgnoreCase))
            .Select(static (file, ct) => new ManifestText(file.Path, file.GetText(ct)?.ToString() ?? string.Empty))
            .Collect();

        context.RegisterSourceOutput(manifests, static (spc, files) => Execute(spc, files));
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<ManifestText> files)
    {
        if (files.IsDefaultOrEmpty)
        {
            return;
        }

        if (files.Length > 1)
        {
            context.ReportDiagnostic(Diagnostic.Create(MultipleManifests, Location.None, string.Join(", ", files.Select(f => f.Path))));
            return;
        }

        CatalogManifest manifest;
        try
        {
            manifest = CatalogManifest.Parse(files[0].Text);
        }
        catch (FormatException ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidManifest, Location.None, files[0].Path, ex.Message));
            return;
        }

        context.AddSource("FoundryModels.g.cs", SourceText.From(Emit(manifest), Encoding.UTF8));
    }

    /// <summary>Generates the source for a manifest.</summary>
    internal static string Emit(CatalogManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by Microsoft.AI.Local.Foundry.Generators from eng/catalog/foundry-models.json. Do not edit.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.AI.Local.Foundry;");
        sb.AppendLine();
        sb.AppendLine("public static partial class FoundryModels");
        sb.AppendLine("{");

        foreach (var model in manifest.Models)
        {
            EmitProperty(sb, model);
        }

        sb.AppendLine("    /// <summary>Gets every supported (not retired) Foundry model handle.</summary>");
        sb.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<global::Microsoft.AI.Local.ILocalModel> All { get; } =");
        sb.AppendLine("    [");
        foreach (var model in manifest.Models.Where(m => m.RetiredMessage is null))
        {
            sb.Append("        ").Append(model.Property).AppendLine(",");
        }

        sb.AppendLine("    ];");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>The catalog-manifest entries, including retired models (used by conformance tests).</summary>");
        sb.AppendLine("    internal static class Descriptors");
        sb.AppendLine("    {");
        foreach (var model in manifest.Models)
        {
            EmitDescriptor(sb, model);
        }

        sb.AppendLine("        public static global::System.Collections.Generic.IReadOnlyList<global::Microsoft.AI.Local.Foundry.FoundryModelDescriptor> All { get; } =");
        sb.AppendLine("        [");
        foreach (var model in manifest.Models)
        {
            sb.Append("            ").Append(model.Property).AppendLine(",");
        }

        sb.AppendLine("        ];");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitProperty(StringBuilder sb, CatalogModel model)
    {
        var (type, factory, taskText) = model.Task switch
        {
            "text-embedding" => ("ITextEmbeddingModel", "TextEmbedding", "text embedding"),
            "speech-to-text" => ("ISpeechToTextModel", "SpeechToText", "speech to text"),
            _ => ("ITextGenerationModel", "TextGeneration", "text generation"),
        };

        sb.Append("    /// <summary>").Append(Xml(model.DisplayName));
        if (model.Publisher is { } publisher)
        {
            sb.Append(" (").Append(Xml(publisher)).Append(')');
        }

        sb.Append(": ").Append(Xml(model.Description ?? taskText)).AppendLine("</summary>");
        sb.AppendLine("    /// <remarks>");
        sb.Append("    /// <para>Foundry Local alias <c>").Append(Xml(model.Alias)).Append("</c>. Task: ").Append(taskText).AppendLine(".</para>");
        var capabilities = Capabilities(model);
        if (capabilities.Length > 0)
        {
            sb.Append("    /// <para>Capabilities: ").Append(capabilities).AppendLine(".</para>");
        }

        sb.Append("    /// <para>Platforms: ").Append(string.Join(", ", model.Platforms)).Append('.');
        if (model.CrossPlatform)
        {
            sb.Append(" Validated cross-platform by the conformance suite.");
        }

        sb.AppendLine("</para>");
        sb.AppendLine("    /// </remarks>");
        if (model.RetiredMessage is { } retired)
        {
            var message = model.RetiredReplacement is { } replacement ? $"{retired} Use FoundryModels.{replacement} instead." : retired;
            sb.Append("    [global::System.Obsolete(").Append(Literal(message)).AppendLine(")]");
        }

        sb.Append("    public static global::Microsoft.AI.Local.").Append(type).Append(' ').Append(model.Property)
            .Append(" { get; } = global::Microsoft.AI.Local.Foundry.FoundryModelFactory.").Append(factory)
            .Append("(Descriptors.").Append(model.Property).AppendLine(");");
        sb.AppendLine();
    }

    private static void EmitDescriptor(StringBuilder sb, CatalogModel model)
    {
        var task = model.Task switch
        {
            "text-embedding" => "TextEmbedding",
            "speech-to-text" => "SpeechToText",
            _ => "TextGeneration",
        };

        sb.Append("        public static readonly global::Microsoft.AI.Local.Foundry.FoundryModelDescriptor ").Append(model.Property).AppendLine(" = new(");
        sb.Append("            ").Append(Literal(model.Alias)).AppendLine(",");
        sb.Append("            ").Append(Literal(model.DisplayName)).AppendLine(",");
        sb.Append("            global::Microsoft.AI.Local.Foundry.FoundryModelTask.").Append(task).AppendLine(",");
        sb.AppendLine("            new global::Microsoft.AI.Local.LocalModelCapabilities");
        sb.AppendLine("            {");
        sb.Append("                SupportsStreaming = ").Append(Bool(model.Streaming)).AppendLine(",");
        sb.Append("                SupportsToolCalling = ").Append(Bool(model.ToolCalling)).AppendLine(",");
        sb.Append("                SupportsImageInput = ").Append(Bool(model.ImageInput)).AppendLine(",");
        sb.Append("                SupportsAudioInput = ").Append(Bool(model.AudioInput)).AppendLine(",");
        sb.Append("                SupportsStructuredOutput = ").Append(Bool(model.StructuredOutput)).AppendLine(",");
        sb.Append("                SupportsReasoning = ").Append(Bool(model.Reasoning)).AppendLine(",");
        sb.Append("                ContextLength = ").Append(Int(model.ContextLength)).AppendLine(",");
        sb.Append("                MaxOutputTokens = ").Append(Int(model.MaxOutputTokens)).AppendLine(",");
        sb.AppendLine("            },");
        sb.Append("            [").Append(string.Join(", ", model.Platforms.Select(Literal))).AppendLine("],");
        sb.Append("            ").Append(model.RetiredMessage is { } retired ? Literal(retired) : "null").AppendLine(");");
        sb.AppendLine();
    }

    private static string Capabilities(CatalogModel model)
    {
        var list = new System.Collections.Generic.List<string>();
        if (model.Streaming)
        {
            list.Add("streaming");
        }

        if (model.ToolCalling)
        {
            list.Add("tool calling");
        }

        if (model.ImageInput)
        {
            list.Add("image input");
        }

        if (model.AudioInput)
        {
            list.Add("audio input");
        }

        if (model.StructuredOutput)
        {
            list.Add("structured output");
        }

        if (model.Reasoning)
        {
            list.Add("reasoning");
        }

        if (model.ContextLength is { } context)
        {
            list.Add(context.ToString("N0", CultureInfo.InvariantCulture) + "-token context");
        }

        return string.Join(", ", list);
    }

    private static string Bool(bool value) => value ? "true" : "false";

    private static string Int(int? value) => value is { } v ? v.ToString(CultureInfo.InvariantCulture) : "null";

    private static string Xml(string text) => text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    private static string Literal(string text)
    {
        var sb = new StringBuilder("\"");
        foreach (var c in text)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (c < 0x20)
                    {
                        sb.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        sb.Append(c);
                    }

                    break;
            }
        }

        return sb.Append('"').ToString();
    }

    private sealed class ManifestText(string path, string text) : IEquatable<ManifestText>
    {
        public string Path { get; } = path;

        public string Text { get; } = text;

        public bool Equals(ManifestText? other) => other is not null && Path == other.Path && Text == other.Text;

        public override bool Equals(object? obj) => Equals(obj as ManifestText);

        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Path) ^ StringComparer.Ordinal.GetHashCode(Text);
    }
}
